version: '3'
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./server.js:/app/server.js
      - ./controllers:/app/controllers
      - ./models:/app/models
      - ./routes:/app/routes
      - /app/node_modules

    env_file:
      - ./.env
    #environment:
    #  - NODE_ENV=development
    #  - MONGO_USER=root
    #  - MONGO_PASSWORD=
    command: npm run dev





