version: '3'
services:
  node-app:
    ports:
      - "5000:5000"
  
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: oculus14

volumes:
  mongo-db: 
     