version: '3'
services:

  nginx:
    ports:
      - "5000:80"
      
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./server.js:/app/server.js
      - ./controllers:/app/controllers
      - ./middleware:/app/middleware
      - ./models:/app/models
      - ./routes:/app/routes
      - /app/node_modules

    env_file:
      - ./.env
    command: npm run dev





