version: '3'
services:
  node-app:
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: 
     